micronaut:
  application:
    name: carrosTestGrpc
datasources:
  default:
    url: jdbc:mysql://localhost/db_carrosTests?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSl=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 123120594
    #    schema-generate: CREATE_DROP
    dialect: org.hibernate.dialect.MySQL5Dialect
jpa.default.properties.hibernate.hbm2ddl.auto: update
